newsletter:
    path:     /
    defaults: { _controller: "ExpresDemoBundle:Newsletter:index" }

newsletter_show:
    path:     /{id}/show
    defaults: { _controller: "ExpresDemoBundle:Newsletter:show" }

newsletter_new:
    path:     /new
    defaults: { _controller: "ExpresDemoBundle:Newsletter:new" }

newsletter_create:
    path:     /create
    defaults: { _controller: "ExpresDemoBundle:Newsletter:create" }
    methods:  POST
