Expres\DemoAdminBundle\Entity\TaskComments:
    type: entity
    table: null
    repositoryClass: Expres\DemoAdminBundle\Entity\TaskCommentsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        taskId:
            type: integer
        created:
            type: datetime
        comment:
            type: text
    lifecycleCallbacks: {  }
