Expres\DemoAdminBundle\Entity\TaskLog:
    type: entity
    table: null
    repositoryClass: Expres\DemoAdminBundle\Entity\TaskLogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        taskId:
            type: integer
        created:
            type: datetime
        stage:
            type: integer
    lifecycleCallbacks: {  }
