<?php

namespace Expres\DemoAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskCommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskCommentsRepository extends EntityRepository
{
}
