<?php

namespace Expres\DemoAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskLogRepository extends EntityRepository
{
}
